{
    "name": "MobilSoft Pazaryeri Core",
    "version": "19.0.1.0.0",
    "category": "Sales/Marketplace",
    "summary": "Tüm pazaryeri entegrasyonları için base framework",
    "author": "MobilSoft",
    "website": "https://www.jokergrubu.com",
    "depends": [
        "base",
        "sale",
        "stock",
        "account",
        "mail",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/marketplace_channel_views.xml",
        "views/marketplace_product_views.xml",
        "views/marketplace_order_views.xml",
        "views/marketplace_sync_log_views.xml",
        "views/menu.xml",
    ],
    "external_dependencies": {
        "python": ["requests"],
    },
    "installable": True,
    "application": True,
    "auto_install": False,
    "license": "LGPL-3",
}
